export enum ErrorCode {
    MISSING_USER_AGENT = "MISSING_USER_AGENT",
    INVALID_REQUEST = "INVALID_REQUEST",
    NOT_FOUND = "NOT_FOUND",
    NOT_AUTHORIZED = "NOT_AUTHORIZED",
    FORBIDDEN = "FORBIDDEN",
    SERVER_ERROR = "SERVER_ERROR",
    RATE_LIMITED = "RATE_LIMITED"
}